# Generated by Codex on 2026-08-24

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0022_auto_20240507_0815"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("U", "UPLOADING"),
                            ("I", "INGESTING"),
                            ("R", "READY"),
                            ("P", "PARTIAL_ERROR"),
                            ("E", "ERROR"),
                            ("N", "RUNNING"),
                        ],
                        default="U",
                        max_length=2,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("F", "FILES"), ("Z", "ZIP")],
                        default="F",
                        max_length=2,
                    ),
                ),
                ("source_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("preset", models.CharField(blank=True, max_length=256, null=True)),
                ("auto_run_preset", models.BooleanField(default=False)),
                ("total_count", models.IntegerField(default=0)),
                ("ready_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("completed_count", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoBatchItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=512)),
                ("original_path", models.CharField(blank=True, max_length=1024)),
                ("source_path", models.CharField(blank=True, max_length=1024, null=True)),
                ("file_size", models.BigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("ingest_error", models.CharField(blank=True, max_length=1024)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "ingest_status",
                    models.CharField(
                        choices=[
                            ("P", "PENDING"),
                            ("I", "INGESTING"),
                            ("R", "READY"),
                            ("E", "ERROR"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="backend.videobatch",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoBatchPluginRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("preset", models.CharField(max_length=256)),
                ("step_index", models.IntegerField(default=0)),
                ("plugin", models.CharField(max_length=256)),
                ("error", models.CharField(blank=True, max_length=1024)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "PENDING"),
                            ("R", "RUNNING"),
                            ("D", "DONE"),
                            ("E", "ERROR"),
                            ("S", "SKIPPED"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_runs",
                        to="backend.videobatch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_runs",
                        to="backend.videobatchitem",
                    ),
                ),
                (
                    "plugin_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.pluginrun",
                    ),
                ),
            ],
        ),
    ]
